### ISSUE TITLE
better way to conditionally set variables in a playbook?

### ISSUE THREAD

**Issue by mwilliammyers** [mwilliammyers/dotfiles#3]
Ref. [ansible.yml:11](https://github.com/mkwmms/dotfiles/blob/a78651827c80bfb6c062143dba28d8a85553dd4e/ansible.yml#L11)

```yml
    # TODO: better way to conditionally set variables in a playbook?
    - name: setup configuration
      set_fact:
        ansible_config_dir: "/usr/local/etc/ansible"
      when: ansible_pkg_mgr == 'homebrew'

…
```
